---
title: "Wyatt's 4th Qtr Grades"
output: html_document
---


```{r setOptions, include=FALSE}
library(googleVis)
op <- options(gvis.plot.tag='chart')
```

```{r, include=FALSE}
library(lubridate)
library(stringr)
library(XML)

# Grades & Attendance
tmp <- readHTMLTable('~/R-Github/R/Wyatt-Grades/data/grades.html')[[1]]
grades <- tmp[c(4:7, 9:10) , c(17, 20, 21)]
colnames(grades) <- c('Grade', 'Absences', 'Tardies')
rownames(grades) <- c('Science', 'Math', 'Band', 'Enrichment', 'Language Arts', 'Social Studies')
grades$Percent <- as.integer(str_sub(grades$Grade, start = 2))
grades$Grade <- as.character(str_sub(grades$Grade, end = 1))
grades <- grades[ , c(1, 4, 2, 3)]
```

```{r, echo=FALSE, results='asis'}
library(knitr)
kable(t(grades), caption = 'Last Updated: Apr 26, 2017')
```

```{r, results='asis', tidy=FALSE, echo=FALSE}
gauges <- gvisGauge(data.frame(Course = rownames(grades), Percent = grades$Percent), 
                    options=list(min=0, max=100, redFrom=0, redTo=69, 
                                 yellowFrom=70, yellowTo=84, greenFrom=85, greenTo=100))
plot(gauges)
```

### Changes
* The band grade dropped from 76% to 66%
* The social studies grade improved from 64% to 69%
