---
title: "Wyatt's Grades on Recent Assignments"
output: html_document
---

```{r setOptions, include=FALSE}
library(googleVis)
op <- options(gvis.plot.tag='chart')
```

```{r, include=FALSE}
library(knitr)
library(lubridate)
library(stringr)
library(XML)

parse_class <- function(filename, dir = '~/R/Wyatt-Grades/data/') {
  x <- readHTMLTable(str_c(dir, filename))[[2]]
  x <- x[2:nrow(x), c(1:3, 9:11)]
  names(x) <- c('Date', 'Category', 'Assignment', 'Score', 'Percent', 'Grade')
  x$Date <- mdy(x$Date)
  x$Score <- as.character(x$Score)
  x$Percent <- as.integer(as.character(x$Percent))
  x$Grade <- factor(x = x$Grade, levels = c('A', 'B', 'C', 'D', 'F'))
  x
}

parse_score <- function(x) {
  tmp <- str_split(x, pattern = "/")
  scored <- sapply(tmp, function(x) x[1])
  scored <- str_replace(scored, "--", "0")
  scored <- sum(as.numeric(scored))
  possible <- sum(as.numeric(sapply(tmp, function(x) x[2])))
  c(scored, possible)
}

classes <- lapply(c('science.html', 'math.html', 'band.html', 'ela.html', 'social-studies.html'), parse_class)
names(classes) <- c('Science', 'Math', 'Band', 'ELA', 'Social-Studies')

# Scores for the past n assignments by class
n.assignments <- 4
last_assignments <- function(x, n = 5) tail(x[date(now()) > x$Date, ], n)
last3 <- lapply(classes, last_assignments, n.assignments)
scores <- lapply(last3, function(x) parse_score(x$Score))
percents <- sapply(scores, function(x) 100 * x[1] / x[2])
```

```{r, results='asis', tidy=FALSE, echo=FALSE}
#tmp <- data.frame(Course = rownames(grades), Percent = grades$Percent)
#gauges <- lapply(1:nrow(tmp), 
#                 function(n) gvisGauge(tmp[n, c('Course', 'Percent')], 
#                                       options=list(min=0, max=100, 
#                                                    redFrom=0, redTo=69, 
#                                                    yellowFrom=70, yellowTo=84, 
#                                                    greenFrom=85, greenTo=100)))
gauges <- gvisGauge(data.frame(Course = names(percents), Percent = round(percents, 1)), 
                    options=list(min=0, max=100, redFrom=0, redTo=69, 
                    yellowFrom=70, yellowTo=84, greenFrom=85, greenTo=100))

plot(gauges)
```


```{r, echo=FALSE, results='asis'}
  tmp <- last3[[4]]
  rownames(tmp) <- 1:n.assignments
  kable(tmp, caption = names(last3)[4])
```

```{r, echo=FALSE, results='asis'}
  tmp <- last3[[5]]
  rownames(tmp) <- 1:n.assignments
  kable(tmp, caption = names(last3)[5])
```
